### ISSUE TITLE
Build issue on Windows

### ISSUE THREAD

**Issue by Cyan4973** [floooh/sokol-samples#9]
Hi @floooh ,

I've been trying to build your impressive `sokol-samples` following [instructions ](https://github.com/floooh/sokol-samples#how-to-build)
on a Windows 10 system, using multiple method,

They all fail at various points in the process.
I was thinking you might be interested in these failures.

#### MinGW64
My preferred environment to compile on Windows is MSYS2/MinGW64.
It's a pretty good combination of familiar Unix environment and tools,
yet producing and using Windows binaries.
It's relatively easy to satisfy all dependency requirements (make, cmake, git, python)
using the `pacman` manager.

Yet, the build process fails at this point : 
```
=== building: win64-vstudio-debug
=== generating: win64-vstudio-debug
config file: C:/path/fips/configs/win64-vstudio-debug.yml
cmake -A "x64" -DCMAKE_BUILD_TYPE=Debug -DFIPS_CONFIG=win64-vstudio-debug -DFIPS_USE_CCACHE=OFF -DFIPS_AUTO_IMPORT=OFF -BC:/path/fips-build/sokol-samples/win64-vstudio-debug -HC:/path/sokol-samples
CMake Error in C:/path/sokol-samples/CMakeLists.txt:
  Generator

    Unix Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
[ERROR] Failed to generate 'win64-vstudio-debug' of project 'sokol-samples'
```

It's not clear what the problem is.
The builder seems confused, between Unix and Windows.

#### MSYS2
My second environment for Windows is MSYS2/MSYS.
This is a close relative, but provides full Posix emulation.
It makes it possible to compile a source code which typically depends on some posix library not available on Windows (or different on Windows).
The problem is, the translation layer can be painfully slow, especially for I/O related events, so it's generally not my first choice.

Anyway, since it's full posix, one could hope that the previous failure would settle for unix and continue ?
Not a chance, it fails well before that point : 
```
Cloning into '/c/path/fips'...
remote: Counting objects: 3859, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 3859 (delta 14), reused 21 (delta 10), pack-reused 3826
Receiving objects: 100% (3859/3859), 1.39 MiB | 395.00 KiB/s, done.
Resolving deltas: 100% (2631/2631), done.
Checking out files: 100% (270/270), done.
Traceback (most recent call last):
  File "./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/c/path/fips/mod/fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "/c/path/fips/verbs/build.py", line 18, in run
    cfg_name = settings.get(proj_dir, 'config')
  File "/c/path/fips/mod/settings.py", line 70, in get
    value = get_default(key)
  File "/c/path/fips/mod/settings.py", line 43, in get_default
    return config.get_default_config()
  File "/c/path/fips/mod/config.py", line 48, in get_default_config
    return default_config[util.get_host_platform()]
  File "/c/path/fips/mod/util.py", line 273, in get_host_platform
    return host_platforms[platform.system()]
KeyError: 'MSYS_NT-10.0'
```

It's worth nothing that, under this environment, the default python version is 3.6.2, which might explain the issue with python script. And although python2 is also installed, I'm unsure how to make it default.

#### Windows (pure) command prompt
Last attempt, using MS Windows environment, regular command prompt.
This is my least preferred choice, mainly because this one use different command and tools, doesn't have a package manager like `pacman`, so it's necessary to find each dependency, install them individually, pollute the `path` with each specific product directory, etc.
But at least, this is pure Windows, and I would expect the Visual Studio experience to work fine.

Well, my first attempt was pretty strange : although I have Visual Studio installed, `cmake` would nonetheless try to use the "GNU make" solution, and would fail, because the path to `make` is hard-coded to `/usr/bin/make` , which feels a bit too "posix" for Windows. I could manually ensure that `make` is present into the `path`, and manually checked that it works, but its path certainly does not look like a posix path.

(...) 

Well, while writing this rather long report, I made a second attempt, and for some reasons unclear to me, this time, `cmake` selected the Visual Studio way. And now I've got a working Visual solution.
And apparently, I don't even need to use it, since nifty `fips` make it possible to select a project and run it directly from command line. Which is great.

I guess this was the intended experience.

**Comment by floooh** [comment]
Yes, I'm afraid you'll have to use Visual Studio on Windows, not any of the Unix environment wrappers. The workflow with fips is mostly the same as on Linux or OSX, but with the Visual Studio toolchain instead of gcc or clang.

Supporting MSYS or MingW64 would 'feather out' into too many different paths (especially for UI samples).

The MSYS_NT-10.0 key error you got looks like a bug in fips though. There is some rudimentary support for either MinGW or MSYS, but that's less tested. I'll open a separate ticket for this error.

**Comment by fr500** [comment]
hello

I'm just getting into sokol, looks like a great framework. But yeah msys2 support is kind of a deal breaker for me. 

Any plans to support MSYS2 better? basically we'd need to use -G"MSYS Makefiles" in cmake and it should work

**Comment by fr500** [comment]
Maybe something like this?
CMAKE_GENERATOR="MSYS Makefiles" ./fips set config linux-make-release
CMAKE_GENERATOR="MSYS Makefiles" ./fips build

It's not working yet, it seems to want to use options in / format (instead of dashes)

```
 CMAKE_GENERATOR="MSYS Makefiles" ./fips build
=== dependency: 'sokol':
dir 'E:/msys64/home/andre/repos/sokol' exists
=== dependency: 'sokol-tools-bin':
dir 'E:/msys64/home/andre/repos/sokol-tools-bin' exists
=== dependency: 'fips-glfw':
dir 'E:/msys64/home/andre/repos/fips-glfw' exists
=== dependency: 'fips-cimgui':
dir 'E:/msys64/home/andre/repos/fips-cimgui' exists
=== dependency: 'fips-imgui':
dir 'E:/msys64/home/andre/repos/fips-imgui' exists
=== dependency: 'fips-libmodplug':
dir 'E:/msys64/home/andre/repos/fips-libmodplug' exists
=== dependency: 'fips-utils':
dir 'E:/msys64/home/andre/repos/fips-utils' exists
=== building: linux-make-release
make -j6
make[1]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
[  1%] Building CXX object fips-imgui_imgui/CMakeFiles/imgui.dir/imgui/imgui.cpp.obj
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: Entering directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
[  2%] Building CXX object fips-cimgui_cimgui/CMakeFiles/cimgui.dir/cimgui/cimgui.cpp.obj
[  3%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/context.c.obj
[  5%] Building C object glfw/CMakeFiles/flextgl.dir/flextgl/flextGL.c.obj
[  5%] Building C object glfw/CMakeFiles/flextgl12.dir/flextgl12/flextGL.c.obj
[  6%] Building CXX object fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/fastmix.cpp.obj
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
cc.exe: error: E:/msys64/MP: No such file or directory
cc.exe: error: E:/msys64/WX: No such file or directory
cc.exe: error: E:/msys64/TC: No such file or directory
cc.exe: error: /errorReport:queue: No such file or directory
cc.exe: error: E:/msys64/DWIN32: No such file or directory
cc.exe: error: E:/msys64/Ox: No such file or directory
cc.exe: error: E:/msys64/DNDEBUG: No such file or directory
cc.exe: error: E:/msys64/MT: No such file or directory
cc.exe: error: E:/msys64/GL: No such file or directory
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
make[2]: *** [fips-imgui_imgui/CMakeFiles/imgui.dir/build.make:64: fips-imgui_imgui/CMakeFiles/imgui.dir/imgui/imgui.cpp.obj] Error 1
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[1]: *** [CMakeFiles/Makefile2:148: fips-imgui_imgui/CMakeFiles/imgui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [fips-glfw_glfw3/CMakeFiles/glfw3.dir/build.make:64: fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/context.c.obj] Error 1
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[1]: *** [CMakeFiles/Makefile2:98: fips-glfw_glfw3/CMakeFiles/glfw3.dir/all] Error 2
make[2]: *** [fips-cimgui_cimgui/CMakeFiles/cimgui.dir/build.make:64: fips-cimgui_cimgui/CMakeFiles/cimgui.dir/cimgui/cimgui.cpp.obj] Error 1
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[1]: *** [CMakeFiles/Makefile2:198: fips-cimgui_cimgui/CMakeFiles/cimgui.dir/all] Error 2
cc.exe: error: E:/msys64/MP: No such file or directory
cc.exe: error: E:/msys64/WX: No such file or directory
cc.exe: error: E:/msys64/TC: No such file or directory
cc.exe: error: /errorReport:queue: No such file or directory
cc.exe: error: E:/msys64/DWIN32: No such file or directory
cc.exe: error: E:/msys64/Ox: No such file or directory
cc.exe: error: E:/msys64/DNDEBUG: No such file or directory
cc.exe: error: E:/msys64/MT: No such file or directory
cc.exe: error: E:/msys64/GL: No such file or directory
cc.exe: error: E:/msys64/MP: No such file or directory
cc.exe: error: E:/msys64/WX: No such file or directory
cc.exe: error: E:/msys64/TC: No such file or directory
cc.exe: error: /errorReport:queue: No such file or directory
cc.exe: error: E:/msys64/DWIN32: No such file or directory
cc.exe: error: E:/msys64/Ox: No such file or directory
cc.exe: error: E:/msys64/DNDEBUG: No such file or directory
cc.exe: error: E:/msys64/MT: No such file or directory
cc.exe: error: E:/msys64/GL: No such file or directory
make[2]: *** [glfw/CMakeFiles/flextgl12.dir/build.make:64: glfw/CMakeFiles/flextgl12.dir/flextgl12/flextGL.c.obj] Error 1
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[2]: *** [glfw/CMakeFiles/flextgl.dir/build.make:64: glfw/CMakeFiles/flextgl.dir/flextgl/flextGL.c.obj] Error 1
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[1]: *** [CMakeFiles/Makefile2:798: glfw/CMakeFiles/flextgl12.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:633: glfw/CMakeFiles/flextgl.dir/all] Error 2
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
make[2]: *** [fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/build.make:64: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/fastmix.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[  7%] Building CXX object fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_669.cpp.obj
[  7%] Building CXX object fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_abc.cpp.obj
[  8%] Building CXX object fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_amf.cpp.obj
[  9%] Building CXX object fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_ams.cpp.obj
[ 10%] Building CXX object fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_dbm.cpp.obj
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
make[2]: *** [fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/build.make:78: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_669.cpp.obj] Error 1
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
make[2]: *** [fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/build.make:92: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_abc.cpp.obj] Error 1
make[2]: *** [fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/build.make:106: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_amf.cpp.obj] Error 1
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
c++.exe: error: E:/msys64/EHsc: No such file or directory
c++.exe: error: E:/msys64/MP: No such file or directory
c++.exe: error: E:/msys64/WX: No such file or directory
c++.exe: error: E:/msys64/TP: No such file or directory
c++.exe: error: E:/msys64/DWIN32: No such file or directory
c++.exe: error: E:/msys64/Ox: No such file or directory
c++.exe: error: E:/msys64/DNDEBUG: No such file or directory
c++.exe: error: E:/msys64/MT: No such file or directory
c++.exe: error: E:/msys64/GL: No such file or directory
make[2]: *** [fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/build.make:134: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_dbm.cpp.obj] Error 1
make[2]: *** [fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/build.make:120: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/libmodplug/src/load_ams.cpp.obj] Error 1
make[2]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make[1]: *** [CMakeFiles/Makefile2:248: fips-libmodplug_libmodplug/CMakeFiles/libmodplug.dir/all] Error 2
make[1]: Leaving directory '/home/andre/repos/fips-build/sokol-samples/linux-make-release'
make: *** [Makefile:84: all] Error 2
[ERROR] Failed to build config 'linux-make-release' of project 'sokol-samples'
```

**Comment by floooh** [comment]
No plans so far sorry, does MSYS2 support all the Windows SDK headers directly? I think last time I looked into it this was the problem.

**Comment by fr500** [comment]
No, not really, if anything, msys2 is just a mingw distribution, it's a posix environment (everything is wrapped) so as long as the cmakelists can be tweaked to treat it like such it should work.
